{% set version = "1.13.2" %}

package:
  name: elixir
  version: {{ version }}

source:
  url: https://github.com/elixir-lang/elixir/archive/v{{ version }}.tar.gz
  sha256: 03afed42dccf4347c4d3ae2b905134093a3ba2245d0d3098d75009a1d659ed1a

build:
  number: 0
  skip: true  # [win]
  script: make prefix=${PREFIX} install

requirements:
  build:
    - git
    - make
  host:
    - erlang >=21.0
  run:
    - erlang >=21.0

test:
  commands:
    - elixir --version
    # this apparently hangs, now
    # - iex --version
    - mix --version

about:
  home: https://elixir-lang.org/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Elixir is a dynamic, functional language designed for building scalable and maintainable applications
  dev_url: https://github.com/elixir-lang/elixir
  doc_url: https://elixir-lang.org/docs.html
  doc_source_url: https://github.com/elixir-lang/elixir/blob/master/lib/elixir/docs.exs

extra:
  recipe-maintainers:
    - bollwyvl
